name: filmster
description: A new Flutter application.

version: 0.0.8+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  http: ^0.12.0+4
  dartpedia: ^1.6.6
  url_launcher: ^5.4.2
  provider: ^4.3.1
  admob_flutter: ^1.0.0-beta.5
  package_info: ^0.4.0+16
  shared_preferences: ^0.5.8
  firebase_analytics: ^6.0.0
  firebase_crashlytics: ^0.1.4+1
  firebase_performance: ^0.4.3
  flutter_svg: ^0.18.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.8.1

flutter_icons:
  ios: true
  android: true
  image_path: "assets/image/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/icons/
    - assets/image/


  fonts:
    - family: Cuprum
      fonts:
        - asset: assets/fonts/Cuprum-Bold.ttf
        - asset: assets/fonts/Cuprum-Regular.ttf
        - asset: assets/fonts/Cuprum-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Cuprum-Italic.ttf
          style: italic
    - family: AmaticSC
      fonts:
        - asset: assets/fonts/AmaticSC-Bold.ttf
          weight: 700
        - asset: assets/fonts/AmaticSC-Regular.ttf
    - family: MPLUSRounded1c
      fonts:
        - asset: assets/fonts/MPLUSRounded1c-Bold.ttf
          weight: 700
        - asset: assets/fonts/MPLUSRounded1c-Regular.ttf
          weight: 400
        - asset: assets/fonts/MPLUSRounded1c-Thin.ttf
          weight: 100
        - asset: assets/fonts/MPLUSRounded1c-Medium.ttf
          weight: 500
        - asset: assets/fonts/MPLUSRounded1c-Light.ttf
          weight: 300
        - asset: assets/fonts/MPLUSRounded1c-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MPLUSRounded1c-Black.ttf
          weight: 900

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
